### ISSUE TITLE
Does this library support parallel/concurrent execution of background tasks?

### ISSUE THREAD

**Issue by davejclausen** [DalSoft/DalSoft.Hosting.BackgroundQueue#2]
Hello, thank you for this library.
I would like to use it - namely because it appears to support background execution of tasks in a parallel/concurrent manner.  I.e. it takes a param "MaxConcurrentCount".

However upon viewing the code, I do not see any parallelism calls.  I just see a standard await call - where execution will wait (await) until that call finishes.

Am I missing anything?  Thank you.

**Comment by DalSoft** [comment]
Hi,

Thanks for raising this issue your not missing anything. Originally it was meant to support concurrent calls, I ran into a production issue with the way exceptions were being handled (TBH I can't rememeber what issue was), you can see where I made the change [here](https://github.com/DalSoft/DalSoft.Hosting.BackgroundQueue/commit/1ea1b8e3555c9c5331ed6df7d27c4455219f722b#diff-220679da65547196bd32e8b17187f2c9)

Feel free to try the older package, that was the only change I made between versions. I'm working on a new version that will have better support for dependency injection, in particularly it will have a concept of scope, that is my priority along with test coverage. Then I will look at making it support parallel calls. I'll update the readme as I can see it is confusing.

**Comment by davejclausen** [comment]
Super - thank you for this info - and thanks again for contributing this library.
