### ISSUE TITLE
inject database context

### ISSUE THREAD

**Issue by alexishughes** [DalSoft/DalSoft.Hosting.BackgroundQueue#4]
I want your system to update my database when the background task has completed, but i cannot use the context from the MVC controller because it has a lifetime of the request only. Can you explain how I can either call some other controller like method or inject a context into the BackgroundQueue.

**Comment by DalSoft** [comment]
Fully supported in [v2.0.0](https://github.com/DalSoft/DalSoft.Hosting.BackgroundQueue/compare/v1.1.1...v2.0.0) 

Updated in README.md has an example showing how to do this in v.2.0.0

v2.0 has a [fully working EF example in the repo](https://github.com/DalSoft/DalSoft.Hosting.BackgroundQueue/tree/master/DalSoft.Hosting.BackgroundQueue.Examples.WebApi)
