### ISSUE TITLE
Scope of CancellationToken

### ISSUE THREAD

**Issue by angrymarker** [DalSoft/DalSoft.Hosting.BackgroundQueue#9]
I found your library on [stackoverflow](https://stackoverflow.com/a/48136348/3965629)

you noted this was created to replace HostingEnvironment.QueueBackgroundWorkItem

For a sanity check, will CancellationToken be called whenever the app pool recycles/is shut down? 

QueueBackgroundWorkItem gives the users a 30 second window to gracefully close it's stuff before forcing everything to end, so i'm hoping CancellationToken.Register will give me the (now 5 second) same grace period

**Comment by DalSoft** [comment]
I  can confirm this to be correct: https://github.com/DalSoft/DalSoft.Hosting.BackgroundQueue/blob/master/DalSoft.Hosting.BackgroundQueue/HostedService.cs

StopAsync is implemented and the cancellation token is honoured. 
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-8.0&tabs=visual-studio
